version: "3.7"

services:
  # Уже рабочий вебсервер с ssl соединением
  webserver:
    build: nginx
    container_name: webserver
    restart: unless-stopped
    # 443 - порт для ssl соединения
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Статические файлы, а также
      # Дирректория webroot, чтобы обновлять сертификаты
      # Можно было бы использовать обычный том
      - ./webroot:/webroot
      - ./nginx/app:/webserver_confs/app
      - ./nginx/ssl:/webserver_confs/ssl
    # Нужный файл - здесь прописано доменное имя к которому обращаются пользователи
    # И на которое у нас уже есть сертификат
    # Используетсяв ./nginx/app.conf.template
    env_file: .env
