version: '3.3'
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  # backend:
  #   build:
  #     context: ./backend
  #   restart: always
  #   volumes: 
  #     - static_value:/app/static/
  #     - media_value:/app/media/  
  #   depends_on:
  #     - db  
  #   env_file: 
  #     - ./.env
 
  # frontend:
  #   build:
  #     context: ./frontend
  #   command: node .output/server/index.mjs

  proxy: 
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./frontend:/frontend
    # depends_on:
    #   - backend
    #   - frontend
    env_file: 
      - ./.env
    command: sh -c "/app/run.sh"

volumes: 
  postgres_data:
  static_value:
  media_value:
  certbot-etc:
  certbot-var: