version: "3.7"

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - ./mysite:/var/www/html
      - ./certbot/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    # environment:
    # # наше доменное имя сайта
    #   - domain=moprules.ru
    #   - email=rav-navini-gego-cutropal@yandex.ru
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./mysite:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email $email --agree-tos --no-eff-email --staging -d $domain

volumes:
  certbot-etc:
  certbot-var:
